DROP TABLE ALUNO CASCADE CONSTRAINTS;

--> CRIA��O DA TABELA ALUNO
CREATE TABLE ALUNO (
    RM          INTEGER,
    NM_ALUNO    VARCHAR2(100)
);

--> PESQUISAR DADOS NA TABELA
SELECT * FROM ALUNO;

--> INSERIR DADOS NA TABELA
INSERT INTO ALUNO VALUES(1, 'ZOINHO');
INSERT INTO ALUNO (RM, NM_ALUNO) VALUES (2, 'JOANA');
INSERT INTO ALUNO (NM_ALUNO, RM) VALUES ('MARIA', 3);
INSERT INTO ALUNO VALUES(4, 'ZEZINHO');

ALTER TABLE ALUNO
ADD CONSTRAINT PK_ALUNO
PRIMARY KEY (RM);

DELETE ALUNO WHERE NM_ALUNO = 'ZEZINHO';
UPDATE ALUNO SET RM=4 WHERE NM_ALUNO = 'ZEZINHO';

COMMIT;

ROLLBACK;

DESC ALUNO;

SELECT CONSTRAINT_NAME, CONSTRAINT_TYPE FROM USER_CONSTRAINTS WHERE TABLE_NAME = 'ALUNO';

--> ALTERAR A ESTRUTURA DA TABELA ADICIONANDO COLUNA
ALTER TABLE ALUNO
ADD STATUS CHAR(1);

ALTER TABLE ALUNO
ADD CONSTRAINT CK_STATUS
CHECK (STATUS IN ('A', 'I'));

SELECT * FROM ALUNO;

UPDATE ALUNO SET STATUS = 'A' WHERE RM = 1;
UPDATE ALUNO SET STATUS = 'I' WHERE RM IN (2,3,4);

--> VALIDANDO O CHECK PARA SABERMOS SE ESTA FUNCIONANDO
UPDATE ALUNO SET STATUS = 'B';

ALTER TABLE ALUNO
    ADD(
        SEXO VARCHAR2(1) CONSTRAINT CK_SEXO CHECK(SEXO IN ('M','F')),
        EMAIL VARCHAR2(50)
);

ALTER TABLE ALUNO
ADD CONSTRAINT UK_EMAIL UNIQUE(EMAIL);

SELECT * FROM ALUNO;

UPDATE ALUNO SET SEXO = 'M' WHERE RM = 1;
UPDATE ALUNO SET SEXO = 'F' WHERE RM = 2;
UPDATE ALUNO SET EMAIL = 'ZOINHO@GMAIL.COM' WHERE RM = 1;

UPDATE ALUNO SET EMAIL = 'ZOINHO@GMAIL.COM' WHERE RM = 2; 
UPDATE ALUNO SET EMAIL = 'JOANA@GMAIL.COM' WHERE RM = 2;

UPDATE ALUNO SET SEXO = 'F', EMAIL = 'MARIA@TERRA.COM.BR' WHERE RM = 3;
UPDATE ALUNO SET SEXO = 'F', EMAIL = 'ZEZINHO@TERRA.COM.BR' WHERE RM = 45;
UPDATE ALUNO SET SEXO = 'F', EMAIL = 'MARIA@TERRA.COM.BR' WHERE RM = 4;

--> alterar o nome de uma coluna existente na tabela
ALTER TABLE ALUNO RENAME COLUMN E_MAIL TO EMAIL;

--> alterar tabela excluindo duas ou mais colunas
ALTER TABLE ALUNO DROP (SEXO, EMAIL);

--> alterar nome de uma tabela
ALTER TABLE ALUNO RENAME TO TESTE;

--> aqui vamos aplenas voltar o da tabela
ALTER TABLE TESTE RENAME TO ALUNO;

--> Drop table <-- 
--> Excluir objetos do banco de dados
DROP TABLE NOME_TABELA

--> FORMAS DE SE CRIAR UMA PRIMARY KEY
DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID_MYTABLE      NUMBER PRIMARY KEY,
    DESCRICAO       VARCHAR(100)
);

INSERT INTO MYTABLE VALUES (1, 'XXXXX');
INSERT INTO MYTABLE VALUES (2, 'XXXXX');

DROP TABLE MYTABLE CASCADE CONSTRAINTS;
CREATE TABLE MYTABLE (
    ID_MYTABLE      NUMBER,
    DESCRICAO       VARCHAR(100),
    PRIMARY KEY (ID_MYTABLE)
);

INSERT INTO MYTABLE VALUES (1, 'XXXXX');
INSERT INTO MYTABLE VALUES (2, 'ZZZZZ');

Select * from mytable;

DROP TABLE MYTABLE;
CREATE TABLE MYTABLE (
    ID_MYTABLE      NUMBER,
    DESCRICAO       VARCHAR(100),
    CONSTRAINT PK_MYTABLE PRIMARY KEY (ID_MYTABLE)
);

INSERT INTO MYTABLE VALUES (1, 'XXXXXX');
INSERT INTO MYTABLE VALUES (2, 'ZZZZZZ');


