DROP TABLE ALUNO CASCADE CONSTRAINTS;
DROP TABLE DISCIPLINA CASCADE CONSTRAINTS;
DROP TABLE NOTA CASCADE CONSTRAINTS;

CREATE TABLE ALUNO(
    COD_ALUNO    NUMBER         NOT NULL,
    NOME         VARCHAR2(50)   NOT NULL,
    CURSO        VARCHAR2(50)   NOT NULL,
    SERIE        VARCHAR2(50)   NOT NULL,
    SEXO         VARCHAR2(1),
    CONSTRAINT PK_COD_ALUNO PRIMARY KEY (COD_ALUNO),
    CONSTRAINT CK_SEXO_ALUNO CHECK (SEXO IN ('M','F'))
);

CREATE TABLE DISCIPLINA(
    COD_DISCIPLINA    NUMBER         NOT NULL,
    TITULO            VARCHAR2(50)   NOT NULL,
    PROFESSOR         VARCHAR2(50)   NOT NULL,
    CONSTRAINT PK_COD_DISCIPLINA PRIMARY KEY (COD_DISCIPLINA)
);

CREATE TABLE NOTA(
    COD_ALUNO         NUMBER         NOT NULL,
    COD_DISCIPLINA    NUMBER         NOT NULL,
    AV1               NUMBER,
    AV2               NUMBER,
    AV3               NUMBER,
    AV4               NUMBER,
    MEDIA             NUMBER,
    RESULTADO         VARCHAR2(50),
    CONSTRAINT FK_COD_ALUNO FOREIGN KEY (COD_ALUNO) REFERENCES ALUNO (COD_ALUNO),
    CONSTRAINT FK_COD_DISCIPLINA FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINA (COD_DISCIPLINA)
);

-- Inserindo dados na tabela ALUNO
INSERT INTO ALUNO (COD_ALUNO, NOME, CURSO, SERIE, SEXO) VALUES (1, 'João Silva', 'Engenharia', '4º', 'M');
INSERT INTO ALUNO (COD_ALUNO, NOME, CURSO, SERIE, SEXO) VALUES (2, 'Maria Souza', 'Direito', '3º', 'F');
INSERT INTO ALUNO (COD_ALUNO, NOME, CURSO, SERIE, SEXO) VALUES (3, 'Carlos Pereira', 'Medicina', '2º', 'M');
INSERT INTO ALUNO (COD_ALUNO, NOME, CURSO, SERIE, SEXO) VALUES (4, 'Ana Lima', 'Arquitetura', '1º', 'F');

-- Inserindo dados na tabela DISCIPLINA
INSERT INTO DISCIPLINA (COD_DISCIPLINA, TITULO, PROFESSOR) VALUES (101, 'Matemática Aplicada', 'Prof. Roberto');
INSERT INTO DISCIPLINA (COD_DISCIPLINA, TITULO, PROFESSOR) VALUES (102, 'Direito Constitucional', 'Prof. Clara');
INSERT INTO DISCIPLINA (COD_DISCIPLINA, TITULO, PROFESSOR) VALUES (103, 'Anatomia Humana', 'Prof. Ricardo');
INSERT INTO DISCIPLINA (COD_DISCIPLINA, TITULO, PROFESSOR) VALUES (104, 'Desenho Técnico', 'Prof. Helena');

-- Inserindo dados na tabela NOTA
INSERT INTO NOTA (COD_ALUNO, COD_DISCIPLINA, AV1, AV2, AV3, AV4, MEDIA, RESULTADO) VALUES (1, 101, 8.0, 7.5, 9.0, 8.5, 8.25, 'Aprovado');
INSERT INTO NOTA (COD_ALUNO, COD_DISCIPLINA, AV1, AV2, AV3, AV4, MEDIA, RESULTADO) VALUES (2, 102, 7.0, 6.5, 8.0, 7.5, 7.25, 'Aprovado');
INSERT INTO NOTA (COD_ALUNO, COD_DISCIPLINA, AV1, AV2, AV3, AV4, MEDIA, RESULTADO) VALUES (3, 103, 9.0, 8.5, 8.0, 9.5, 8.75, 'Aprovado');
INSERT INTO NOTA (COD_ALUNO, COD_DISCIPLINA, AV1, AV2, AV3, AV4, MEDIA, RESULTADO) VALUES (4, 104, 6.5, 7.0, 6.0, 5.0, 6.75, 'Reprovado');



--> SELECT: Para apresentar todos os dados de uma tabela:
--> SELECT * FROM nome_da_tabela
SELECT * FROM Aluno;

